

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/startup_db?serverTimezone=Asia/Seoul
    username: starter
    password: starter


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true


logging:
  level:
    org:
      springframework:
        security: Debug
    root: info
    org.springframework.web: debug
    org.hibernate: info

#------------------------------------------------
# controller.view-name : /html/* -> thymeleaf
#------------------------------------------------
  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:/templates
    suffix: .html
    view-names: /html/*